= {lab_name}

== Introduction press it in front

[[openshift-acm]]

===  OpenShift console access & RHACM console access

NOTE: The Red Hat Advanced Cluster Management for Kubernetes (RHACM) Console is now integrated with OpenShift Console, to access it please select *All Clusters* from the dropdown menu once you log in. 

Your OpenShift cluster console is available in the right panel. In case you want to open it in another window it is here: {openshift_cluster_console_url}[window=blank]

Administrator login is available with:

[cols="1,1"]
|===
| *Username:* | {openshift_cluster_admin_username}
| *Password:* | {openshift_cluster_admin_password}
|===

[[acs]]
=== RHACS console access

Your RHACS Console is available in the right panel. In case you want to open it in another window it is here:  {acs_route}[window=blank]

Administrator login is available with:

[cols="1,1"]
|===
| *RHACS Console Username:* | {acs_portal_username} 
| *RHACS Console Password:* | {acs_portal_password} 
|===

=== roxctl CLI verification

Since roxctl hasn't been installed yet, we will install it now. along with a few other key pieces of software. (I know, blame the Ops team :) )

*Procedure*

[start=1]
. Run the following command.

[source,sh,subs="attributes",role=execute]
----
roxctl --insecure-skip-tls-verify -e "$ROX_CENTRAL_ADDRESS:443" central whoami
----

== Lab Modules

* xref:module-01.adoc[Module 1: Operations & Security]
* xref:module-02.adoc[Module 2: Assurance]
* xref:module-03.adoc[Module 3: Technology & Supply Chain]
* xref:module-04.adoc[Module 4: Data & AI]

Click next to get started.